description: >-
  We are a Tech Startup focus on cybersecurity industry. We believe we can do 
  much more with new approaches adapted to the daily operations for those who 
  are fighting cybercrime everyday.

sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - Dockerfile
  - docker-compose.yml
  - CNAME
  - README.md
